export enum HTTP_ERROR_TYPES {
  CONFLICT = 'CONFLICT',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  SERVER_ERROR = 'SERVER_ERROR',
  BAD_REQUEST_ERROR = 'BAD_REQUEST_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
}

export enum AUTH_FORM_ERRORS {
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  WRONG_CREDENTIALS = 'WRONG_CREDENTIALS',
  ACCOUNT_NOT_VERIFIED = 'ACCOUNT_NOT_VERIFIED',
  SERVER_ERROR = 'SERVER_ERROR',
}

export interface IError<T = HTTP_ERROR_TYPES | AUTH_FORM_ERRORS> {
  readonly httpError: T;
  readonly httpStatus?: number;
  readonly message: string;
}

export interface IAuthError extends IError<AUTH_FORM_ERRORS> {}
